# Serena Project Configuration for my-nvim-config
project:
  name: "my-nvim-config"
  type: "mixed"  # Lua, Shell, YAML
  root: "."
  
language_servers:
  lua:
    enabled: true
    server: lua-language-server
  
exclude:
  - ".git/"
  - "*.log"
  - "*.bak"
  - "node_modules/"
  
tools:
  search_symbol:
    include_tests: true
    include_private: false
  
  apply_edits:
    auto_format: true
    verify_syntax: true
